
// This file has been generated by the GUI designer. Do not modify.
namespace DashCam
{
	public partial class Main
	{
		private global::Gtk.HBox hbox3;

		private global::Gtk.VBox vbox3;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Image image7;

		private global::Gtk.Image image9;

		private global::Gtk.Image image11;

		private global::Gtk.Button button5;

		private global::Gtk.Button button9;

		private global::Gtk.Button button7;

		private global::Gtk.Image Preview;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget DashCam.Main
			this.WidthRequest = 640;
			this.HeightRequest = 400;
			this.Name = "DashCam.Main";
			this.Title = global::Mono.Unix.Catalog.GetString("Main");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowGrow = false;
			this.DefaultWidth = 640;
			this.DefaultHeight = 400;
			this.Decorated = false;
			// Container child DashCam.Main.Gtk.Container+ContainerChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.image7 = new global::Gtk.Image();
			this.image7.WidthRequest = 20;
			this.image7.HeightRequest = 20;
			this.image7.Name = "image7";
			this.image7.Xpad = 10;
			this.image7.Ypad = 10;
			this.image7.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-media-record", global::Gtk.IconSize.Dialog);
			this.hbox4.Add(this.image7);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.image7]));
			w1.Position = 0;
			w1.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.image9 = new global::Gtk.Image();
			this.image9.WidthRequest = 20;
			this.image9.HeightRequest = 20;
			this.image9.Name = "image9";
			this.image9.Xpad = 10;
			this.image9.Ypad = 10;
			this.image9.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-refresh", global::Gtk.IconSize.Dialog);
			this.hbox4.Add(this.image9);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.image9]));
			w2.Position = 1;
			w2.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.image11 = new global::Gtk.Image();
			this.image11.WidthRequest = 20;
			this.image11.HeightRequest = 20;
			this.image11.Name = "image11";
			this.image11.Xpad = 10;
			this.image11.Ypad = 10;
			this.image11.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-disconnect", global::Gtk.IconSize.Dialog);
			this.hbox4.Add(this.image11);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.image11]));
			w3.Position = 2;
			w3.Fill = false;
			this.vbox3.Add(this.hbox4);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox4]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			w4.Padding = ((uint)(10));
			// Container child vbox3.Gtk.Box+BoxChild
			this.button5 = new global::Gtk.Button();
			this.button5.WidthRequest = 100;
			this.button5.HeightRequest = 150;
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseUnderline = true;
			this.button5.BorderWidth = ((uint)(5));
			this.button5.Label = global::Mono.Unix.Catalog.GetString("Recordings");
			this.vbox3.Add(this.button5);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.button5]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.button9 = new global::Gtk.Button();
			this.button9.WidthRequest = 100;
			this.button9.HeightRequest = 50;
			this.button9.CanFocus = true;
			this.button9.Name = "button9";
			this.button9.UseUnderline = true;
			this.button9.BorderWidth = ((uint)(5));
			this.button9.Label = global::Mono.Unix.Catalog.GetString("Settings");
			this.vbox3.Add(this.button9);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.button9]));
			w6.PackType = ((global::Gtk.PackType)(1));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.button7 = new global::Gtk.Button();
			this.button7.WidthRequest = 100;
			this.button7.HeightRequest = 50;
			this.button7.CanFocus = true;
			this.button7.Name = "button7";
			this.button7.UseUnderline = true;
			this.button7.BorderWidth = ((uint)(5));
			this.button7.Label = global::Mono.Unix.Catalog.GetString("Stop\nRecording");
			this.vbox3.Add(this.button7);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.button7]));
			w7.PackType = ((global::Gtk.PackType)(1));
			w7.Position = 3;
			w7.Expand = false;
			w7.Fill = false;
			this.hbox3.Add(this.vbox3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vbox3]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.Preview = new global::Gtk.Image();
			this.Preview.WidthRequest = 540;
			this.Preview.HeightRequest = 400;
			this.Preview.Name = "Preview";
			this.hbox3.Add(this.Preview);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.Preview]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.Add(this.hbox3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Show();
			this.button5.Clicked += new global::System.EventHandler(this.Recordings_Click);
		}
	}
}
