
// This file has been generated by the GUI designer. Do not modify.
namespace DashCam
{
	public partial class Recordings
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget DashCam.Recordings
			this.WidthRequest = 640;
			this.HeightRequest = 400;
			this.Name = "DashCam.Recordings";
			this.Title = global::Mono.Unix.Catalog.GetString("Recordings");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowGrow = false;
			this.DefaultWidth = 640;
			this.DefaultHeight = 400;
			this.Decorated = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Show();
		}
	}
}
